### ISSUE TITLE
script: cannot open typescript: Permission denied

### ISSUE THREAD

**Issue by fronkr56** [binhex/arch-rtorrentvpn#1]
I'm getting this error when I try to run after the most recent update. I've attached a log from the unraid container. I'm very excited about this container and will be testing this container often to work out the bugs. Thanks
[binhex-rtorrentvpn.log.txt](https://github.com/binhex/arch-rtorrentvpn/files/190988/binhex-rtorrentvpn.log.txt)

**Comment by binhex** [comment]
this issue is now resolved, please pull down the latest docker image.

**Comment by fronkr56** [comment]
Still having issues on unRAID, the error has changed but it's still permission denied. I've tried looking through it and i have no idea why it's still an issue.
[rtorrentvpn.log.txt](https://github.com/binhex/arch-rtorrentvpn/files/207215/rtorrentvpn.log.txt)
