### ISSUE TITLE
Cannot access rutorrent from outside

### ISSUE THREAD

**Issue by ZataH** [binhex/arch-rtorrentvpn#8]
I cannot access my webui from outside of my lan. I have added iptable mangle.
Are there any other modules I need to load?

**Comment by binhex** [comment]
No, you only need iptable mangle module, the other thing you need to do is port forward the webui on your router and it should work fine.

**Comment by ZataH** [comment]
I already have it port forwarded, but it doesnt work.
The port forward worked earlier, on another installation og rtorrent, so I know there is nothing wrong with the forward

**Comment by binhex** [comment]
All I can say is this does work, I have it

**Comment by binhex** [comment]
All I can say is this does work, I have it

**Comment by ZataH** [comment]
rutorrent on port 9443. It worked earlier on my unraid. But I have migrated all my docker to a Ubuntu box. And for some reason, it doesnt work here. It works fine on my local lan, just not from outside.

**Comment by binhex** [comment]
ok thanks for confirming, so that should work fine for the webui (rutorrent), it could well be a local fireewall issue, do you have a firewall running on ubuntu?, i believe the later versions of ubuntu have the firewall turned on by default. also can you check the supervisord.log file (located in the volume map for /config), this should echo out whether it was able to successfully use the loaded iptable mangle module or not.

**Comment by binhex** [comment]
assuming issue is fixed, please re-open if this isnt the case.

**Comment by ZataH** [comment]
Sorry I forgot to reply. I didnt fix my issue. I ended up going back to UnRAID for other reasons, and therefor my issues also went away :)

**Comment by binhex** [comment]
hehe ok fair enough, im pretty confident it would be a local firewall issue that was blocking you, i will leave this as closed as youve done the wise thing and moved back to unraid :-)

**Comment by aspeer06** [comment]
I'm actually struggling with this exact issue on Ubuntu 16.04.5
No local firewall and confirmed multiple times on edge firewall that it's configured properly.
Works internally perfect but externally I get nothing.

from supervisord.log
[info] iptable_mangle support detected, adding fwmark for tables

FWIW my network is a 10.0.0.0/8 defined so the VPN tun0 exists within my internal address space.
